include: package:code_secure_flutter/analysis_options.yaml 

analyzer:
  plugins:
    - custom_lint
    
# configure the custom lint rules
custom_lint:
  rules:
    - require_parameter_assert:
      error_severity: Warning