name: showable_dialog
description: A package to automatically generate `show` helper functions for dialogs
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  flutter:
    sdk: flutter
  build: ^2.4.0
  source_gen: ^1.4.0
  analyzer: ^6.2.0

dev_dependencies:
  build_runner: ^2.4.0